# Generated by Django 5.0.4 on 2024-05-02 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('heroes', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('names', models.CharField(default='', max_length=30)),
                ('category', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Mystery', 'Mystery'), ('Adventure', 'Adventure')], default='', max_length=30)),
                ('era', models.CharField(choices=[('Past', 'Past'), ('Present', 'Present'), ('Future', 'Future'), ('Urban', 'Urban'), ('Prehistoric', 'Prehistoric'), ('Medieval', 'Medieval')], default='', max_length=15)),
                ('antiheroes', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('magic', models.BooleanField(default=False)),
                ('science', models.BooleanField(default=False)),
                ('stars', models.BooleanField(default=False)),
                ('seas', models.BooleanField(default=False)),
                ('side_characters', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1)),
                ('place', models.CharField(default='', max_length=30)),
                ('leadership', models.CharField(choices=[('Monarchy', 'Monarchy'), ('Democracy', 'Democracy'), ('Anarchy', 'Anarchy'), ('Dictatorship', 'Dictatorship'), ('Managed Democracy', 'Managed Democracy')], default='Monarchy', max_length=30)),
                ('Story_generated_by_prompts', models.CharField(default='', editable=False, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
