# Generated by Django 5.0.4 on 2024-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='story',
        ),
        migrations.AddField(
            model_name='react',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='heroes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='names',
            field=models.CharField(default='', max_length=30),
        ),
    ]
