# Generated by Django 5.0.4 on 2024-05-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='Story_generated_by_prompts',
        ),
        migrations.AddField(
            model_name='story',
            name='Construct_prompts',
            field=models.CharField(default='', editable=False, max_length=120),
        ),
    ]
