# Generated by Django 5.0.4 on 2024-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0002_remove_react_story_react_category_react_heroes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='era',
            field=models.CharField(choices=[('Past', 'Past'), ('Present', 'Present'), ('Future', 'Future'), ('Urbain', 'Urbain')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='react',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Mystery', 'Mystery'), ('Adventure', 'Adventure')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='react',
            name='heroes',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4')], default='1', max_length=2),
        ),
    ]
