# Generated by Django 5.0.4 on 2024-04-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0003_react_era_alter_react_category_alter_react_heroes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='era',
            field=models.CharField(choices=[('Past', 'Past'), ('Present', 'Present'), ('Future', 'Future'), ('Urban', 'Urban')], default='', max_length=30),
        ),
    ]
