# Generated by Django 5.0.4 on 2024-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0004_alter_react_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='antiheroes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='react',
            name='era',
            field=models.CharField(choices=[('Past', 'Past'), ('Present', 'Present'), ('Future', 'Future'), ('Urban', 'Urban')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='react',
            name='heroes',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4')], default='1', max_length=1),
        ),
    ]
