# Generated by Django 5.0.4 on 2024-04-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0005_react_antiheroes_alter_react_era_alter_react_heroes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='names',
        ),
    ]
