# Generated by Django 5.0.4 on 2024-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0006_remove_react_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='antiheroes',
        ),
        migrations.AddField(
            model_name='react',
            name='names',
            field=models.CharField(default='', max_length=30),
        ),
    ]
