# Generated by Django 5.0.4 on 2024-04-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiwriter', '0007_remove_react_antiheroes_react_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='magics',
            field=models.BooleanField(default=False),
        ),
    ]
